---
- name: Remove conflicting packages
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    purge: yes

- name: Ensure apt package index is updated
  apt:
    update_cache: yes

- name: Install required packages for Docker installation
  apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create directory for Docker GPG keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker's official repository to apt sources
  copy:
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    dest: /etc/apt/sources.list.d/docker.list

- name: Update apt package index again
  apt:
    update_cache: yes

- name: Install fontconfig
  ansible.builtin.apt:
    name: fontconfig
    state: present

- name: Install OpenJDK 17
  ansible.builtin.apt:
    name: openjdk-17-jre
    state: present

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Notify reinitialization of Worker Session
  debug:
    msg: >
      The user {{ ansible_user }} has been added to the docker group.
      Please, if your are already logged, log out and log back in to apply group membership changes.